### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by sve-odoo** [oci-labs/pdfjs-dist-viewer-min#1]
Dear,

Could you please provide any clue on how to use this?
I am trying to embed that in a Vue.js app.

Thanks in advance!

**Comment by goatandsheep** [comment]
It hasn't been rebuilt in a while and they didn't leave instructions on how to build it. Best to leave it alone.

**Comment by VoltiSubito** [comment]
Hello @sve-odoo,

This is just a minified build of Mozilla's pdf.js project.  The [project website](https://mozilla.github.io/pdf.js/) has a lot of documentation on its use.
